### ISSUE TITLE
Implement an installer with ezplatform.com data

### ISSUE THREAD

**Issue by nicolas-bastien** [ezsystems/ezplatform-com#54]
## Description

Project doesn't have any installer to ease project setup
Dump from ezplatform.com are available at this urls : 

- https://ezplatform.com/dumps/ezplatform_page_storage.tar.bz2
- https://ezplatform.com/dumps/ezplatform_page_db.sql.bz2

**Important** : storage file is pretty big as releases files are stored on ezplatform.com
https://github.com/ezsystems/ezplatform-com/issues/66

## Todo

Implement an installer which will download the dump and install it

---
## Initial Issue

After a clean installation with app/console ezplatform:install clean as it's written in INSTALL.md, we have the following error on /.

    Could not find 'eZ\Publish\SPI\Persistence\Content\Type' with identifier 'ID: layout, Status: 0'

@bdunogier gave me this link https://doc.ez.no/pages/viewpage.action?pageId=32867328 but it's not obvious when you arrive on this repo.

I think it can be good to make an installer for that as it's done in the demo project ?

Do you agree on that @SylvainGuittard  ?

+ do you think that we can centralize the install documentation inside this repo instead of pointing to confluence ?

**Comment by clash82** [comment]
Hello @nicolas-bastien, nice to meet you :)

`clean` is only for clean ezplatform installs.

You shouldn't use it to install ezplatform-com project.
There is a sql dump file that you should use to import database structure (sql file path is included in the documentation page).

**Comment by SylvainGuittard** [comment]
Hi @nicolas-bastien!

Thanks for reporting this issue.

A documentation page will be available soon on ezplatform.com. This page will describe all the steps in order to install ezplatform.com locally.

About INSTALL.md: this repo is based on the ezplatform repo and this file has not been updated with specific instructions. I think we can do it at the same time as we do the doc page on ezplatform.com

**Comment by nicolas-bastien** [comment]
Hi thanks for your answers, 

Right now, links on dumps on the demo page ends on 404.

I'll wait you ping me on this issue when the doc is available, I'll be happy to test the installation.
