### ISSUE TITLE
Code enhancement

### ISSUE THREAD

**Issue by nicolas-bastien** [ezsystems/ezplatform-com#59]
Refactor service declaration and layout view like we did on ezplatform-demo.

- https://github.com/ezsystems/ezplatform-demo/pull/48
- https://github.com/ezsystems/ezplatform-demo/pull/47

**Comment by clash82** [comment]
+1

**Comment by nicolas-bastien** [comment]
Done

**Comment by nicolas-bastien** [comment]
https://github.com/ezsystems/ezplatform-com/pull/60
